CREATE TABLE USUARIO (
    ID_USUARIO INT GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    FOTO BYTEA,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE QUADRO (
    ID_QUADRO INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_QUADRO)
);

CREATE TABLE COR (
    ID_COR INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(20),
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_COR)
);

CREATE TABLE RAIA (
    ID_RAIA INT GENERATED ALWAYS AS IDENTITY,
    QTD_MAX INT NOT NULL CHECK (QTD_MAX > 0),
    NOME VARCHAR(50) NOT NULL,
    ID_QUADRO INT NOT NULL,
    PRIMARY KEY (ID_RAIA),
    FOREIGN KEY (ID_QUADRO) 
        REFERENCES QUADRO(ID_QUADRO)
        ON DELETE CASCADE
);

CREATE TABLE CARTAO (
    ID_CARTAO INT GENERATED ALWAYS AS IDENTITY,
    DATA_INICIO DATE NOT NULL,
    DATA_FINAL DATE NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOME VARCHAR(50) NOT NULL,
	DESCRICAO TEXT,
    ORDEM INT NOT NULL DEFAULT 0,
    ID_RAIA INT,
    ID_COR INT,
    PRIMARY KEY (ID_CARTAO),
    CHECK (DATA_FINAL >= DATA_INICIO),
    FOREIGN KEY (ID_RAIA) 
        REFERENCES RAIA(ID_RAIA)
        ON DELETE SET NULL,
    FOREIGN KEY (ID_COR) 
        REFERENCES COR(ID_COR)
        ON DELETE SET NULL
);

CREATE TABLE USUARIO_CARTAO (
    ID_USUARIO INT,
    ID_CARTAO INT,
    DATA_ASSOCIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    TIPO_ACESSO VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_CARTAO),
    CHECK (TIPO_ACESSO IN ('DONO', 'EDITOR', 'LEITOR')),
    FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_CARTAO) 
        REFERENCES CARTAO(ID_CARTAO)
        ON DELETE CASCADE
);

CREATE TABLE USUARIO_QUADRO (
    ID_USUARIO INT,
    ID_QUADRO INT,
    DATA_ASSOCIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    TIPO_ACESSO VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_QUADRO),
    CHECK (TIPO_ACESSO IN ('DONO', 'EDITOR', 'LEITOR')),
    FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_QUADRO) 
        REFERENCES QUADRO(ID_QUADRO)
        ON DELETE CASCADE
);
